const contents = {
  1: [
    ['./media/projects/Carnival/1.jpg', ' Carnival Crepes Bentleigh'],
    ['./media/projects/Carnival/2.jpg', '  '],
    ['./media/projects/Carnival/3.jpg', ' '],
    ['./media/projects/Carnival/4.jpg', '  '],
    ['./media/projects/Carnival/5.jpg', ' '],
    ['./media/projects/Carnival/6.jpg', ' '],
    ['./media/projects/Carnival/7.jpg', '  '],
    ['./media/projects/Carnival/8.jpg', ' '],
    ['./media/projects/Carnival/9.jpg', '  '],
    ['./media/projects/Carnival/10.jpg', ' '],
    ['./media/projects/Carnival/11.jpg', ' '],
    ['./media/projects/Carnival/12.jpg', '  '],
    ['./media/projects/Carnival/13.jpg', ' '],
    ['./media/projects/Carnival/14.jpg', ' '],
  ],
  2: [
    ['./media/projects/HaPortrait/ha1.jpg', ' Melbourne, 2020'],
    [
      './media/projects/HaPortrait/ha2.jpg',
      'Ha is turning 26 this year and wanted to have some portraits to mark her birthday. ',
    ],
    [
      './media/projects/HaPortrait/ha3.jpg',
      'This photoshoot was set up in her own garden and living room during the quarantine period in Melbourne. ',
    ],
    [
      './media/projects/HaPortrait/ha4.jpg',
      ' The mood she wants to deliver in the portrait was a little moody, a little easy and natural following her movement. ',
    ],
    ['./media/projects/HaPortrait/ha9.jpg', ' '],
    ['./media/projects/HaPortrait/ha10.jpg', ' '],
    ['./media/projects/HaPortrait/ha11.jpg', ' '],
    ['./media/projects/HaPortrait/ha13.jpg', ' '],
    ['./media/projects/HaPortrait/ha5.jpg', ' '],
    ['./media/projects/HaPortrait/ha6.jpg', ' '],
    ['./media/projects/HaPortrait/ha7.jpg', ' '],
    ['./media/projects/HaPortrait/ha8.jpg', ''],
    ['./media/projects/HaPortrait/ha12.jpg', ' '],
  ],
  3: [
    ['./media/projects/Cibi/cib1.jpg', 'CIBI & The General Hub '],
    ['./media/projects/Cibi/cib2.jpg', 'Melbourne, 2020 '],
    ['./media/projects/Cibi/cib3.jpg', ' https://cibi.com.au/'],
    [
      './media/projects/Cibi/cib4.jpg',
      ' https://www.thehubgeneralstore.com.au/ ',
    ],
    ['./media/projects/Cibi/cib5.jpg', ' '],
    ['./media/projects/Cibi/cib6.jpg', ' '],
    ['./media/projects/Cibi/cib7.jpg', ' '],
    ['./media/projects/Cibi/cib8.jpg', ' '],
    ['./media/projects/Cibi/cib9.jpg', ' '],
    ['./media/projects/Cibi/cib10.jpg', ' '],
    ['./media/projects/Cibi/cib11.jpg', ' '],
    ['./media/projects/Cibi/cib12.jpg', '  '],
    ['./media/projects/Cibi/cib13.jpg', ' '],
    ['./media/projects/Cibi/cib14.jpg', ' '],
    ['./media/projects/Cibi/cib15.jpg', ' '],
    ['./media/projects/Cibi/cib16.jpg', ' '],
  ],
  4: [
    [
      './media/projects/Sea color/sea1.jpg',
      'We learned to love the tranquil and calm atmosphere this city has been giving us. Surrounded by a breathtaking wide open space of coastline, its sunset is something we never want to miss when heading out to the beach. ',
    ],
    ['./media/projects/Sea color/sea2.jpg', ' '],
    ['./media/projects/Sea color/sea3.jpg', ' '],
    ['./media/projects/Sea color/sea4.jpg', '  '],
    ['./media/projects/Sea color/sea5.jpg', ' '],
    ['./media/projects/Sea color/sea6.jpg', ' '],
    ['./media/projects/Sea color/sea7.jpg', ' '],
    ['./media/projects/Sea color/sea8.jpg', ' '],
    ['./media/projects/Sea color/sea9.jpg', ' '],
  ],
  5: [
    ['./media/projects/AdelaideNight/adel7.jpg', ' Adelaide 2019 '],
    ['./media/projects/AdelaideNight/adel8.jpg', ' '],
    ['./media/projects/AdelaideNight/adel9.jpg', ' '],
    ['./media/projects/AdelaideNight/adel10.jpg', '  '],
    ['./media/projects/AdelaideNight/adel11.jpg', ' '],
    ['./media/projects/AdelaideNight/adel1.jpg', ' '],
    ['./media/projects/AdelaideNight/adel2.jpg', '  '],
    ['./media/projects/AdelaideNight/adel3.jpg', ' '],
    ['./media/projects/AdelaideNight/adel4.jpg', '  '],
    ['./media/projects/AdelaideNight/adel5.jpg', ' '],
    ['./media/projects/AdelaideNight/adel6.jpg', ' '],
  ],
  6: [
    ['./media/projects/SydneyBar/syd1.jpg', 'Sydney, 2019 '],
    ['./media/projects/SydneyBar/syd2.jpg', ' '],
    ['./media/projects/SydneyBar/syd3.jpg', ' Palmer & Co. Prohibition Bar'],
    ['./media/projects/SydneyBar/syd4.jpg', '  '],
    ['./media/projects/SydneyBar/syd5.jpg', ' '],
    ['./media/projects/SydneyBar/syd6.jpg', ' '],
  ],
  7: [
    ['./media/projects/Turkey/turk5.jpg', 'Istanbul, 2018 '],
    ['./media/projects/Turkey/turk2.jpg', ' '],
    [
      './media/projects/Turkey/turk3.jpg',
      'No words could describe how much we love Istanbul in night time when streetlight goes up and the people go out.  ',
    ],
    [
      './media/projects/Turkey/turk4.jpg',
      'Strolling through the narrow streets and lanes in Beyoglu,',
    ],
    [
      './media/projects/Turkey/turk7.jpg',
      'we enjoyed ourevening just by looking at the hustle and bustle atmosphere and energy this place had to offer. ',
    ],
    ['./media/projects/Turkey/turk6.jpg', ' '],
    [
      './media/projects/Turkey/turk8.jpg',
      'İstiklal Caddesi was packed with people. ',
    ],
  ],
  8: [
    ['./media/projects/Melbourne/mel1.jpg', ' '],
    ['./media/projects/Melbourne/mel2.jpg', ' '],
    ['./media/projects/Melbourne/mel3.jpg', ' '],
    ['./media/projects/Melbourne/mel4.jpg', '  '],
    ['./media/projects/Melbourne/mel5.jpg', ' '],
    ['./media/projects/Melbourne/mel6.jpg', ' '],
    ['./media/projects/Melbourne/mel7.jpg', ' '],
    ['./media/projects/Melbourne/mel8.jpg', ' '],
    ['./media/projects/Melbourne/mel9.jpg', ' '],
    ['./media/projects/Melbourne/mel10.jpg', ' '],
    ['./media/projects/Melbourne/mel11.jpg', ' '],
    ['./media/projects/Melbourne/mel12.jpg', ' '],
    ['./media/projects/Melbourne/mel13.jpg', ' '],
    ['./media/projects/Melbourne/mel14.jpg', ' '],
  ],
  9: [
    ['./media/projects/BATHOUR/1.jpg', ' BATHOUR is an Australian brand with vegan & cruelty-free bath & body products built on the notion that self-care should be therapeutic, simple & filtered out from all the stress & irritation. Being inspired by the golden hour, our mission is to make your bath hour the most gorgeous time of your day. '],
    ['./media/projects/BATHOUR/2.jpg', ' SERENITY is a social media campaign that promote the brand oils, bubble bath, soap bars and bath soaks products'],
    ['./media/projects/BATHOUR/5.jpg', 'This campaign aims to target a young niche customer segment that values self-care and high quality skin-care products '],
    ['./media/projects/BATHOUR/6.jpg', 'In this campaign, I came up with ideas and moodboard to set the consistency between the message and visual elements. '],
    ['./media/projects/BATHOUR/7.jpg', ' It was a fun process working/directing art/producsing great content with the photographer and model on photoshoot day. '],
    ['./media/projects/BATHOUR/8.jpg', ' Visit instagram @bathour.official for more information. '],
    ['./media/projects/BATHOUR/9.jpg', ' BATHOUR Bath Soaks'],
    ['./media/projects/BATHOUR/10.jpg', ' BATHOUR Body Oil'],
    ['./media/projects/BATHOUR/11.jpg', ' '],
    ['./media/projects/BATHOUR/12.jpg', ' Instagram Grid for social media planning'],
    ['./media/projects/BATHOUR/13.jpg', ' Social Media Schedule'],
    ['./media/projects/BATHOUR/14.jpg', ' '],
    ['./media/projects/BATHOUR/15.jpg', ' BATHOUR Launch Campaign'],
    ['./media/projects/BATHOUR/16.jpg', ' '],
    ['./media/projects/BATHOUR/17.jpg', ' '],
    ['./media/projects/BATHOUR/18.jpg', ' '],
    ['./media/projects/BATHOUR/19.jpg', ''],
    ['./media/projects/BATHOUR/20.jpg', ' '],
    
  ],
  // 9: [
  //   ['./media/projects/HaPortrait2/ha5.jpg', ' '],
  //   ['./media/projects/HaPortrait2/ha6.jpg', ' '],
  //   ['./media/projects/HaPortrait2/ha7.jpg', ' '],
  //   ['./media/projects/HaPortrait2/ha8.jpg', ''],
  //   ['./media/projects/HaPortrait2/ha12.jpg', ' '],
  // ],
  10: [
    ['./media/projects/Sea mono/mono1.jpg', ' '],
    ['./media/projects/Sea mono/mono2.jpg', ' '],
    ['./media/projects/Sea mono/mono3.jpg', ' '],
    ['./media/projects/Sea mono/mono4.jpg', '  '],
    ['./media/projects/Sea mono/mono5.jpg', ' '],
    ['./media/projects/Sea mono/mono6.jpg', ' '],
    ['./media/projects/Sea mono/mono7.jpg', ' '],
    ['./media/projects/Sea mono/mono8.jpg', ' '],
    ['./media/projects/Sea mono/mono9.jpg', ' '],
    ['./media/projects/Sea mono/mono10.jpg', ' '],
    ['./media/projects/Sea mono/mono11.jpg', ' '],
  ],
  11: [
    ['./media/projects/Black Orange/bl01.jpg', ' '],
    ['./media/projects/Black Orange/bl02.jpg', ' '],
    ['./media/projects/Black Orange/bl03.jpg', ' '],
    ['./media/projects/Black Orange/bl04.jpg', ' '],
    ['./media/projects/Black Orange/bl05.jpg', ' '],
    ['./media/projects/Black Orange/bl06.jpg', ' '],
    ['./media/projects/Black Orange/bl07.jpg', ' '],
    ['./media/projects/Black Orange/bl08.jpg', ' '],
    ['./media/projects/Black Orange/bl09.jpg', ' '],
    ['./media/projects/Black Orange/bl10.jpg', ' '],
    ['./media/projects/Black Orange/bl11.jpg', ' '],
    ['./media/projects/Black Orange/bl12.jpg', ' '],
    ['./media/projects/Black Orange/bl13.jpg', ' '],
    ['./media/projects/Black Orange/bl14.jpg', ' '],
    ['./media/projects/Black Orange/bl15.jpg', ' '],
  ],
};
